-- Tiles
loadTexture("./res/regionmap/tile_atlas.png", "tile_atlas"              , Vector2i(0, 0)   , Vector2i(640, 320))
loadTexture("./res/regionmap/tile_atlas.png", "tile_template"           , Vector2i(64, 256), Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_grass_warm"         , Vector2i(0, 0)   , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_grass_cold"         , Vector2i(64, 0)  , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_grass_subtropical"  , Vector2i(128, 0) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_grass_mediterranean", Vector2i(64, 96) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_grass_tropical"     , Vector2i(192, 0) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_grass_tundra"       , Vector2i(256, 0) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_ocean"              , Vector2i(320, 0) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_river"              , Vector2i(384, 0) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_black"              , Vector2i(0, 288) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_black_empty"        , Vector2i(0, 256) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_template_direction" , Vector2i(64, 288), Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_height_dirt"        , Vector2i(0, 32)  , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_height_stone"       , Vector2i(64, 32) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_resource_stone"     , Vector2i(0, 64)  , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_resource_flint"     , Vector2i(64, 64) , Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_resource_clay"      , Vector2i(128, 64), Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_resource_copper"    , Vector2i(192, 64), Vector2i(64, 32))
loadTexture("./res/regionmap/tile_atlas.png", "tile_resource_tin"       , Vector2i(256, 64), Vector2i(64, 32))

-- Trees
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_foliage_atlas", Vector2i(0, 0)   , Vector2i(768, 1152))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_beech"   , Vector2i(0, 0)   , Vector2i(64, 96))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_oak"     , Vector2i(64, 0)  , Vector2i(64, 96))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_maple"   , Vector2i(128, 0) , Vector2i(64, 96))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_spruce_1", Vector2i(0, 96)  , Vector2i(64, 96))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_spruce_2", Vector2i(64, 96) , Vector2i(64, 96))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_cypress" , Vector2i(0, 192) , Vector2i(64, 96))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_acacia"  , Vector2i(64, 192), Vector2i(128, 96))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_palm"    , Vector2i(0, 288) , Vector2i(64, 96))
loadTexture("./res/regionmap/tile_atlas_foliage.png", "tile_tree_pine"    , Vector2i(704, 0) , Vector2i(64, 192))

-- Buildings
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_atlas"          , Vector2i(0, 0)  , Vector2i(1024, 1024))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_house"          , Vector2i(0, 0)  , Vector2i(128, 128))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_hunter"         , Vector2i(128, 0), Vector2i(128, 128))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_woodcutter"     , Vector2i(256, 0), Vector2i(128, 128))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_quarry"         , Vector2i(384, 0), Vector2i(128, 128))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_flint_collector", Vector2i(512, 0), Vector2i(128, 128))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_gatherer"       , Vector2i(640, 0), Vector2i(128, 128))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_water_collector", Vector2i(768, 0), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_well"           , Vector2i(832, 0), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/buildings_primitive.png", "building_toolmaker"      , Vector2i(896, 0), Vector2i(128, 128))
loadTexture("./res/regionmap/buildings/animalspot_deer.png"    , "animalspot_deer"         , Vector2i(0, 0)  , Vector2i(128, 128))

-- Dirt paths
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_horizontal"   , Vector2i(0, 0)   , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_vertical"     , Vector2i(0, 64)  , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_cross"        , Vector2i(64, 0)  , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_point"        , Vector2i(64, 64) , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_turn_up"      , Vector2i(128, 0) , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_turn_down"    , Vector2i(128, 64), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_turn_right"   , Vector2i(192, 0) , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_turn_left"    , Vector2i(192, 64), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_without_down" , Vector2i(256, 0) , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_without_top"  , Vector2i(256, 64), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_without_left" , Vector2i(320, 0) , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_dirt_without_right", Vector2i(320, 64), Vector2i(64, 64))

-- Stone paths
loadTexture("./res/regionmap/buildings/path.png", "path_stone_horizontal",    Vector2i(0, 128)  , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_vertical",      Vector2i(0, 192)  , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_cross",         Vector2i(64, 128) , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_point",         Vector2i(64, 192) , Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_turn_up",       Vector2i(128, 128), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_turn_down",     Vector2i(128, 192), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_turn_right",    Vector2i(192, 128), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_turn_left",     Vector2i(192, 192), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_without_down",  Vector2i(256, 128), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_without_top",   Vector2i(256, 192), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_without_left",  Vector2i(320, 128), Vector2i(64, 64))
loadTexture("./res/regionmap/buildings/path.png", "path_stone_without_right", Vector2i(320, 192), Vector2i(64, 64))

-- Highlight templates
loadTexture("./res/regionmap/highlight_template.png", "template_highlight_1x1", Vector2i(0, 0)  , Vector2i(64,  32))
loadTexture("./res/regionmap/highlight_template.png", "template_highlight_2x2", Vector2i(64, 0) , Vector2i(128, 64))
loadTexture("./res/regionmap/highlight_template.png", "template_highlight_3x3", Vector2i(192, 0), Vector2i(192, 96))
loadTexture("./res/regionmap/highlight_template.png", "template_highlight_4x4", Vector2i(384, 0), Vector2i(256, 128))