loadTexture("./res/ui/template/icon_template.png"                 , "icon_default"                          , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_path_dirt.png"               , "icon_template_path_dirt"               , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_path_stone.png"              , "icon_template_path_stone"              , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_farmhouse.png"      , "icon_template_building_gatherer"       , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_woodcutter.png"     , "icon_template_building_woodcutter"     , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_quarry.png"         , "icon_template_building_quarry"         , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_house.png"          , "icon_template_building_house"          , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_flint.png"          , "icon_template_building_flint_collector", Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_hunter.png"         , "icon_template_building_hunter"         , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_toolmaker.png"      , "icon_template_building_toolmaker"      , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_well.png"           , "icon_template_building_well"           , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/buildings/icon_building_water_collector.png", "icon_template_building_water_collector", Vector2i(0, 0), Vector2i(48, 48))

loadTexture("./res/ui/items/icon_item_flint.png"  , "icon_template_item_flint"  , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/items/icon_item_stone.png"  , "icon_template_item_stone"  , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/items/icon_item_wood.png"   , "icon_template_item_wood"   , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/items/icon_item_leather.png", "icon_template_item_leather", Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/items/icon_item_meat.png"   , "icon_template_item_meat"   , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/items/icon_item_grain.png"  , "icon_template_item_grain"  , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/items/icon_item_water.png"  , "icon_template_item_water"  , Vector2i(0, 0), Vector2i(48, 48))
loadTexture("./res/ui/items/icon_item_tools.png"  , "icon_template_item_tools"  , Vector2i(0, 0), Vector2i(48, 48))

loadTexture("./res/ui/template/template.png", "ui_base_top_left"               , Vector2i(0, 0)    , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_top_right"              , Vector2i(128, 0)  , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_bottom_left"            , Vector2i(0, 128)  , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_bottom_right"           , Vector2i(128, 128), Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_middle"                 , Vector2i(64, 64)  , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_top"                    , Vector2i(64, 0)   , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_left"                   , Vector2i(0, 64)   , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_right"                  , Vector2i(128, 64) , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_bottom"                 , Vector2i(64, 128) , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_small_horizontal_left"  , Vector2i(0, 192)  , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_small_horizontal_right" , Vector2i(128, 192), Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_small_horizontal_middle", Vector2i(64, 192) , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_small_vertical_top"     , Vector2i(192, 0)  , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_small_vertical_bottom"  , Vector2i(192, 128), Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_small_vertical_middle"  , Vector2i(192, 64) , Vector2i(32, 32))
loadTexture("./res/ui/template/template.png", "ui_base_single"                 , Vector2i(192, 192), Vector2i(32, 32))

loadTexture("./res/ui/template/button.png",  "button_ui_base_top_left"               , Vector2i(0, 0)  , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_top_right"              , Vector2i(16, 0) , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_bottom_left"            , Vector2i(0, 16) , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_bottom_right"           , Vector2i(16, 16), Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_top"                    , Vector2i(8, 0)  , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_left"                   , Vector2i(0, 8)  , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_right"                  , Vector2i(16, 8) , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_bottom"                 , Vector2i(8, 16) , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_middle"                 , Vector2i(8, 8)  , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_small_horizontal_left"  , Vector2i(0, 24) , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_small_horizontal_right" , Vector2i(16, 24), Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_small_horizontal_middle", Vector2i(8, 24) , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_small_vertical_top"     , Vector2i(24, 0) , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_small_vertical_bottom"  , Vector2i(24, 16), Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_small_vertical_middle"  , Vector2i(24, 8) , Vector2i(8, 8))
loadTexture("./res/ui/template/button.png",  "button_ui_base_single"                 , Vector2i(24, 24), Vector2i(8, 8))

loadTexture("./res/ui/template/template_black.png", "widget_black_base_top_left"               , Vector2i(0, 0)    , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_top_right"              , Vector2i(128, 0)  , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_bottom_left"            , Vector2i(0, 128)  , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_bottom_right"           , Vector2i(128, 128), Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_middle"                 , Vector2i(64, 64)  , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_top"                    , Vector2i(64, 0)   , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_left"                   , Vector2i(0, 64)   , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_right"                  , Vector2i(128, 64) , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_bottom"                 , Vector2i(64, 128) , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_small_horizontal_left"  , Vector2i(0, 192)  , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_small_horizontal_right" , Vector2i(128, 192), Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_small_horizontal_middle", Vector2i(64, 192) , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_small_vertical_top"     , Vector2i(192, 0)  , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_small_vertical_bottom"  , Vector2i(192, 128), Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_small_vertical_middle"  , Vector2i(192, 64) , Vector2i(64, 64))
loadTexture("./res/ui/template/template_black.png", "widget_black_base_single"                 , Vector2i(192, 192), Vector2i(64, 64))

loadTexture("./res/ui/template/button_black.png",  "button_black_base_top_left"               , Vector2i(0, 0)  , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_top_right"              , Vector2i(16, 0) , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_bottom_left"            , Vector2i(0, 16) , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_bottom_right"           , Vector2i(16, 16), Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_top"                    , Vector2i(8, 0)  , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_left"                   , Vector2i(0, 8)  , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_right"                  , Vector2i(16, 8) , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_bottom"                 , Vector2i(8, 16) , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_middle"                 , Vector2i(8, 8)  , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_small_horizontal_left"  , Vector2i(0, 24) , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_small_horizontal_right" , Vector2i(16, 24), Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_small_horizontal_middle", Vector2i(8, 24) , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_small_vertical_top"     , Vector2i(24, 0) , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_small_vertical_bottom"  , Vector2i(24, 16), Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_small_vertical_middle"  , Vector2i(24, 8) , Vector2i(8, 8))
loadTexture("./res/ui/template/button_black.png",  "button_black_base_single"                 , Vector2i(24, 24), Vector2i(8, 8))

loadFont("./res/font/garamond.ttf", "garamond")
loadFont("./res/font/proggy.ttf", "proggy")

-- Building icons
createIcon("icon_template_path_dirt")
createIcon("icon_template_path_stone")
createIcon("icon_template_building_gatherer")
createIcon("icon_template_building_woodcutter")
createIcon("icon_template_building_quarry")
createIcon("icon_template_building_house")
createIcon("icon_template_building_flint_collector")
createIcon("icon_template_building_hunter")
createIcon("icon_template_building_toolmaker")
createIcon("icon_template_building_well")
createIcon("icon_template_building_water_collector")

-- Item / resource icons
createIcon("icon_template_item_flint")
createIcon("icon_template_item_stone")
createIcon("icon_template_item_wood")
createIcon("icon_template_item_leather")
createIcon("icon_template_item_meat")
createIcon("icon_template_item_grain")
createIcon("icon_template_item_water")
createIcon("icon_template_item_tools")